config/routes.rb
Re::Application.routes.draw do
  root :to => "admin/contacts#index_contacts"
  #  Translate::Routes.translation_ui(map) if RAILS_ENV != "production"

    #  https://github.com/ccoenen/rails-translate
    scope '/translate' do
      match '/translate_list', :to => 'translate#index'
      match '/translate', :to => 'translate#translate'
      match '/translate_reload', :to => 'translate#reload'
    end
  
  resources :navigations do
    collection do
      get :cities
      get :quarters
      get :update_address
      get :clean_cache
      get :terms
    end
  end


  namespace :admin do

    resources :statistics do
      collection do
        get :offers_by_team
        get :do_offers_by_team
        get :full_report
        get :do_full_report
      end
    end
    
    resources :contacts do
      collection do
        get :index_clients
        get :index_contacts
        get :check
      end
      member do
        get :add
        get :tab_contact
        get :tab_projects
        get :tab_sells
        get :tab_buys
        get :show_offers
      end

      resources :buys do
        collection do
          get :tab_basic_data
          get :tab_search_results
          get :show_attachments
        end
        member do
          get :add_search_criterias
          get :buy_search_result
          get :change_buy_status
        end
        resources :buy_addresses
        resources :attachments 
        resources :search_criterias do
          member do
            get :property_type_keywords
            get :criteria_search_result
          end
        end
      end

      resources :sells do
        resources :pictures do
          collection do
            get :reload_pictures
          end
        end
      end

      resources :projects do
        resources :project_sells, :as => :sells
        member do
          get :tab_project_sells
        end
      end

    end # end contacts

    namespace :indexes do
      resources :sells do
        collection do
          get :print_sells
          get :user_offers
        end
        member do
          get :print
        end
      end

      resources :projects, :except => [:new, :create] do
        resources :project_sells, :as => :sells
        
        collection do
          get :print_projects
          get :user_projects
        end
        member do
          get :print
        end
      end

      resources :buys do
        collection do
          get :print_buys
          get :user_offers
        end
      end
    end # end indexes
      
    resources :roles
    resources :users do
      collection do
        get :help
      end
      member do
        get :activate
      end

    end

    resources :navigations do
      collection do
        get :nomenclatures
        get :guest_screen
      end
    end

    resources :countries
    resources :districts
    resources :municipalities do
      collection do
        get :load_districts
      end
    end
    
    resources :cities do
      resources :quarters do
        collection do
          get :add_multiple
          post :do_add_multiple
        end
      end
      
      collection do
        get :load_districts
        get :load_municipalities
        get :load_places
      end
    end
    
    resources :offices
    resources :teams do
      collection do
        get :update_team_users
      end


    end
    resources :spheres
    resources :contact_categories
    resources :phones
    resources :phone_types
    resources :internet_comunicators
    resources :internet_comunicator_types
    resources :exposure_types
    resources :construction_types
    resources :property_functions
    resources :property_types
    resources :heating_types
    resources :infrastructure_types
    resources :road_types
    resources :room_types
    resources :apartment_types
    resources :rooms
    resources :buildings
    resources :building_types
    resources :fence_types
    resources :property_locations
    resources :property_category_locations
    resources :keywords
    resources :validation_types
    resources :offer_types
    resources :inspections
    #resources :pictures
    resources :furnishes
    resources :sources
    resources :statuses
    resources :buy_statuses
    resources :standart_choices
    resources :project_stages
    resources :floor_types
    resources :street_types
    resources :canceled_types

    resources :index_sells do
      member do
        get :print
      end
    end

    resources :index_projects do
      member do
        get :print
        get :sells
      end
    end

    resources :addresses do
      collection do
        get :get_districts
        get :get_cities
      end
    end

  end

  match '/' => 'admin/contacts#index'
  resource :account, :controller => "users"
  resources :users
  resource :user_session
  resources :password_resets
  match '/:controller(/:action(/:id))'
end

__END__

ActionController::Routing::Routes.draw do |map|  

  
  #  Translate::Routes.translation_ui(map) if RAILS_ENV != "production"
  
  map.resources  :navigations,
    :collection => [:cities]

  map.namespace :admin do |admin|
    admin.resources :contacts,
      :collection => {
      :index_clients => :get,
      :check => :get
    },
      :member => {
      :add => :get,
      :tab_projects => :get,
      :tab_sells => :get,
      :tab_buys => :get
    } do |contact|
        
      contact.resources :buys,
        :member => {
        :add_search_criterias => :get,
        :buy_search_result => :get,
        :change_buy_status => :get,
      } do |buy|
        buy.resources :buy_addresses
        buy.resources :search_criterias,
          :member => {
          :property_type_keywords => :any,
          :criteria_search_result => :get,
        }
      end

      contact.resources :sells, :member => {:print => :get}

      contact.resources :projects, :member => {
        :print => :get,
        :tab_project_sells => :get,
      } do |project|
        project.resources :sells, :controller => "project_sells"
      end

      admin.namespace :indexes do |index|

        index.resources :sells,
          :member => {:print => :get},
          :collection => {
          :print_sells => :get,
          :user_offers => :get
        }

        index.resources :projects,
          :member => {:print => :get},
          :collection => {
          :print_projects => :get,
          :user_projects => :get
        } do |project|
          project.resources :sells
        end

        index.resources :buys,
          :member => {:print => :get},
          :collection => {
          :print_buys => :get,
          :user_offers => :get
        }
      end

    end

    admin.resources :roles

    admin.resources :users,
      :collection => {:help => :get},
      :member => {:activate => :get}

    admin.resources  :navigations, 
      :collection => [:nomenclatures, :guest_screen]

    admin.resources :countries
    admin.resources :districts

    admin.resources :municipalities,
      :collection => {:load_districts => :get}

    admin.resources :cities,
      :has_many => :quarters,
      :collection => {
      :load_municipalities => :any,
      :load_places => :any,
    }
    
    admin.resources :quarters, :collection => {
      :add_multiple => :get,
      :do_add_multiple => :post
    }
    admin.resources :offices

    admin.resources :teams, 
      :collection => {:update_team_users => :get}

    admin.resources :spheres
    admin.resources :contact_categories
    admin.resources :phones
    admin.resources :phone_types
    admin.resources :internet_comunicators
    admin.resources :internet_comunicator_types
    admin.resources :exposure_types
    admin.resources :construction_types
    admin.resources :property_functions
    admin.resources :property_types
    admin.resources :heating_types
    admin.resources :infrastructure_types
    admin.resources :road_types
    admin.resources :room_types
    admin.resources :apartment_types
    admin.resources :rooms
    admin.resources :buildings
    admin.resources :building_types
    admin.resources :fence_types
    admin.resources :property_locations
    admin.resources :property_category_locations
    admin.resources :keywords
    admin.resources :validation_types
    admin.resources :offer_types
    admin.resources :inspections
    admin.resources :pictures
    admin.resources :furnishes
    admin.resources :sources
    admin.resources :statuses
    admin.resources :buy_statuses
    admin.resources :standart_choices
    admin.resources :project_stages

    admin.resources :index_sells, 
      :except => [:new, :create],
      :member => {:print => :get}
    
    admin.resources :index_projects, 
      :except => [:new, :create],
      :member => {
      :print => :get,
      :sells => :get
    }

    admin.resources :addresses,
      :collection => {
      :update_address=> :get,
      :get_districts => :get,
      :get_cities => :get
    }
  end

  map.root :controller => "admin/contacts", :action => 'index'

  map.resource :account, :controller => "users"
  map.resources :users
  map.resource :user_session
  map.resources :password_resets
  
  # See how all your routes lay out with "rake routes"

  # Install the default routes as the lowest priority.
  # Note: These default routes make all actions in every controller accessible via GET requests. You should
  # consider removing or commenting them out if you're using named routes and resources.
  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end
#== Route Map
# Generated on 10 Dec 2010 10:57
#
#                                                     root        /(.:format)                                                                                    {:action=>"index_contacts", :controller=>"admin/contacts"}

app/controllers/admin/addresses_controller.rb
class Admin::AddressesController < Admin::BaseController

  def index
    @address = Address.first
  end
  
  def show
    @address = Address.find(params[:id])
  end

  def render_map
    respond_to do |format|
      format.js {
        address = Geokit::Geocoders::GoogleGeocoder.geocode(params[:address])
        @map = GoogleMap::Map.new
        @map.markers << GoogleMap::Marker.new(:map => @map,
          :icon => GoogleMap::SmallIcon.new(@map, 'blue'),
          :lat => address.lat,
          :lng => address.lng,
          :open_infoWindow => true,
          :html => address.to_geocodeable_s)
        @map.zoom = 16
        @map1 = @map.to_html
      }
    end
  end

  def new
    @address = User.first.office.address
  end
  
  def create
    @address = Address.new(params[:address])
    if @address.save
      flash[:notice] = "Successfully created address."
      redirect_to @address
    else
      render :action => 'new'
    end
  end
  
  def edit
    @address = Address.find(params[:id])
  end
  
  def update
    @address = Address.find(params[:id])
    @address.reload
    if @address.update_attributes(params[:address])
      render :partial => "show_address", :layout => nil
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @address = Address.find(params[:id])
    @address.destroy
    flash[:notice] = "Successfully destroyed address."
    redirect_to addresses_url
  end

  def get_districts
    respond_to do |format|
      format.js {
        @quarters = Quarter.all(:include => :translations,
          :conditions => ["quarter_translations.name LIKE ?", "%#{params[:q]}%"],
          :limit => params[:limit]
        )
        @quarters.map!{|quarter|
          "#{quarter.city.municipality.district.country.name} -> #{quarter.city.municipality.district.name} -> #{quarter.city.municipality.name} -> #{quarter.city.name} -> #{quarter.name}\n"
        }

        @cities = City.all(:include => :translations,
          :conditions => ["city_translations.name LIKE ?", "%#{params[:q]}%"],
          :limit => params[:limit]
        )
        @cities.map!{|city|
          "#{city.municipality.district.country.name} -> #{city.municipality.district.name} -> #{city.municipality.name} -> #{city.municipality.name}\n"
        }

        @municipalities = Municipality.all(:include => :translations,
          :conditions => ["municipality_translations.name LIKE ?", "%#{params[:q]}%"],
          :limit => params[:limit]
        )
        @municipalities.map!{|municipality|
          "#{municipality.district.country.name} -> #{municipality.district.name} -> #{municipality.name}\n"
        }


        @districts = District.all(:include => :translations,
          :conditions => ["district_translations.name LIKE ?", "%#{params[:q]}%"],
          :limit => params[:limit]
        )
        @districts.map!{|district| "#{district.country.name} -> #{district.name}\n"}

        @places =  @quarters + @cities + @municipalities + @districts

      }
    end

  end

end

app/helpers/addresses_helper.rb
module AddressesHelper

  def address_for(current_address)
    address = {:countries => '', :districts => '', :municiaplities => '', :quarters => ''}
    #    countries = Country.all
    # TODO - да се направи с кеш
    countries = $cache[Country]

    raise "Contact your system administrator for this problem" if countries.nil?
    
    selected_country = current_address.country_id.nil? ? countries.first.id.to_i : current_address.country.id.to_i
    address[:countries] = {:options => countries, :selected => selected_country.to_i}

    districts = $cache["District"].select{|d| d.country_id == selected_country}
    selected_district = current_address.district_id.to_i
    address[:districts] = {:options => districts, :selected => selected_district.to_i}

    municipalities = $cache["Municipality"].select{|m| m.district_id == selected_district}
    selected_municipality = current_address.municipality_id.to_i
    address[:municipalities] = {:options => municipalities, :selected => selected_municipality}

    # TODO: City
    #    cities = $cache["City"].select{|c| c.municipality_id == selected_municipality}
    cities = City.find_all_by_municipality_id(selected_municipality, :include => [:quarters])
    selected_city = current_address.city_id.to_i
    address[:cities] = {:options => cities, :selected => selected_city}

    quarters = $cache["Quarter"].select{|q| q.city_id == selected_city}
    selected_quarter = current_address.quarter_id.to_i
    address[:quarters] = {:options => quarters, :selected => selected_quarter}

    return address
  end

  def show_map(address)
    address = address.to_geo_code
    
    map = GoogleMap::Map.new
    if address.success?
      if address.all.size == 1
        map.markers << GoogleMap::Marker.new(:map => map,
          :icon => GoogleMap::SmallIcon.new(map, 'blue'),
          :lat => address.lat,
          :lng => address.lng,
          :open_infoWindow => true,
          :html => address.to_geocodeable_s + "<br/>lat: #{address.lat} lng: #{address.lng}")
        map.zoom = 15

        map_content = "
              #{map.to_html}
              <div style='width: 800px; height: 400px;'>
                #{map.div}
              </div>"
      else
        addresses = address.all
          
        map_content = ''
        addresses.each_index do |index|
          map_content += link_to_remote addresses[index].to_geocodeable_s,
            :url => { :action => "render_map", :controller => 'admin/addresses', :address => addresses[index].to_geocodeable_s} unless index == 0
        end
      end
      
      content_tag :div, :id => 'map1' do
        map_content
      end
    else
      map_content = 'Адреса не може да бъде намерен на картата !'
    end

  end

  def get_address_from_search search
    
    fields = {
      :address_country_id_equals => :country_id,
      :address_district_id_equals => :district_id,
      :address_municipality_id_equals => :municipality_id,
      :address_city_id_equals => :city_id,
      :address_quarter_id_equals => :quarter_id,
      :address_street_equals => :street,
      :address_number_equals => :number,
    }
    translated_fields = {}
    search.conditions.each do |key, value|
      new_key = fields[key]
      translated_fields[new_key] = value if !value.blank? and key.to_s =~ /address/
    end
    
    Address.new(translated_fields)
  end

  def edit_address(form_builder, address)
    
  end

  def readonly_option readonly_fields, field
    if readonly_fields.include?(field)
      {:readonly => "readonly"}
    else
      {}
    end
  end
  
end

app/views/admin/addresses/_address_form.html.erb
<%# address = address_for(f.object.new_record? ? current_user.office.address : f.object) %>
<%
address = address_for(f.object)
%>

<script type="text/javascript" charset="utf-8">
  jQuery(function($) {
    address_elements = ["country_id", "district_id", "municipality_id", "city_id" ];

    for (var i in address_elements) {
      $("#" + address_elements[i]).change(function(event) {
        element = $(event.target);
        var input_value = element.val();
        var input_id = element.attr("id");
        var data = {
          input_id: input_id,
          input_value: input_value
        };
        $.ajax({
          // type:"POST",
          url: '<%= update_address_navigations_url() %>',
          data: data,
          cache: false,
          async: false,
          success: function (html) {
            // $('#property_type_keywords').html(html);
          }
        });
        event.preventDefault();
        event.stopImmediatePropagation();
        return false;
      });
    }
    
  })
</script>


<div class="address" id="<%= address.object_id %>">

  <%= field_set_tag t("address", :scope => [:admin, :contacts, :form]), :id => "address" do %>
    <div class="left">
      <%= f.label "country_id", Country.model_name.human %>
      <%= f.collection_select("country_id", address[:countries][:options], :id, :name, {
          :include_blank => true,
          :selected => address[:countries][:selected]
        }, # .merge(readonly_option(readonly_fields, :country_id))
        {:id => "country_id"})
    %>
      <br/>
      <%= f.label "district_id", District.model_name.human %>
      <%= f.collection_select("district_id", address[:districts][:options], :id, :name, {:include_blank => true, :selected => address[:districts][:selected]}, {:id => "district_id"}) %>
      <br/>

      <%= f.label "municipality_id", Municipality.model_name.human %>
      <%= f.collection_select("municipality_id", address[:municipalities][:options], :id, :name, {:include_blank => true, :selected => address[:municipalities][:selected]}, {:id => "municipality_id"}) %>
      <br/>

      <%= f.label "city_id", City.model_name.human %>
      <%= f.collection_select("city_id", address[:cities][:options], :id, :name_with_type, {:include_blank => true, :selected => address[:cities][:selected]}, {:id => "city_id"}) %>
      <br/>
      <%= f.label "quarter_id", Quarter.model_name.human %>
      <%= f.collection_select("quarter_id", address[:quarters][:options], :id, :name,
        {
          :include_blank => true,
          :selected => address[:quarters][:selected]
        },
        {
          :id => "quarter_id"
        }
      ) %>
    </div>

    <div class="right">
      <div>
        <%= f.collection_select(:street_type_id, StreetType.all, :id, :name,
          { :include_blank => true},
          { :id => "street_type_id"})
      %>
        <%= f.text_field :street, :style => "width: 167px;", :class => 'inline', :title =>  Address.human_attribute_name("street_hint"), :id => 'street'%>
      </div>
      <div>
        <%= f.label :building, Address.human_attribute_name("building") %>
        <%= f.text_field :building, :id => 'building' %>

        <%= f.label :number, Address.human_attribute_name("number"), :style => "width: 15px;" %>
        <%= f.text_field :number, :id => 'street_number' %>

        <%= f.label :entrance, Address.human_attribute_name("entrance"), :style => "width: 15px;" %>
        <%= f.text_field :entrance %>
      </div>

      <div>
        <%= f.label :floor, Address.human_attribute_name("floor"), :style => "width: 15px;" %>
  <%# f.text_field :floor %>
        <%= f.collection_select("floor_type_id", FloorType.all, :id, :name,
          {:include_blank => true}, {:id => "floor_type_id"}
        ) %>

        <%= f.label :apartment, Address.human_attribute_name("apartment") %>
        <%= f.text_field :apartment %>
      </div>

      <div class="bottom">
  <%# f.label :description, Address.human_attribute_name("description") %>
        <%= f.text_area :description, :class => "inline", :style => "width: 300px;height:54px", :title => Address.human_attribute_name("description") %>
      </div>

    </div>


  <% end %>
</div>

<div>
<%# show_map(f.object) %>
</div>

app/views/admin/addresses/_map.html.erb
<%= map.to_html %>
<div style="width: 500px; height: 500px;">
  <%= map.div %>
</div>

app/views/admin/addresses/_search_form.html.erb
<%  address = address_for(default_address) %>

<%= field_set_tag t("address", :scope => [:admin, :contacts, :form]), :id => "address" do %>
  <div style="display: inline-block; float: left">
    <%= f.label "address_country_id_equals", Country.model_name.human(:name => "name")%>
  <%= f.collection_select("address_country_id_equals", address[:countries][:options], :id, :name, {:include_blank => true, :selected => address[:countries][:selected]}, {:id => "country_id"}) %>
    <%= observe_field :country_id,
      :url => { :controller => "addresses", :action => :update_address },
      :with => :country_id
  %>
  </div>

  <div style="display: inline-block; float: right">
    <%= f.label "address_district_id_equals", District.model_name.human(:name => "name") %>
    <%= f.collection_select("address_district_id_equals", address[:districts][:options], :id, :name, {:include_blank => true, :selected => address[:districts][:selected]}, {:id => "district_id"}) %>
    <%= observe_field :district_id,
      :url => { :controller => "addresses", :action => :update_address },
      :with => :district_id
  %>
    <br/>

    <%= f.label "address_municipality_id_equals", Municipality.model_name.human(:name => "name") %>
    <%= f.collection_select("address_municipality_id_equals", address[:municipalities][:options], :id, :name, {:include_blank => true, :selected => address[:municipalities][:selected]}, {:id => "municipality_id"}) %>
    <%= observe_field :municipality_id,
      :url => { :controller => "addresses", :action => :update_address },
      :with => :municipality_id
  %>
    <br/>

    <%= f.label "address_city_id_equals", City.model_name.human(:name => "name")%>
    <%= f.collection_select("address_city_id_equals", address[:cities][:options], :id, :name, {:include_blank => true, :selected => address[:cities][:selected]}, {:id => "city_id"}) %>
    <%= observe_field :city_id,
      :url => { :controller => "addresses", :action => :update_address },
      :with => :city_id
  %>
    <br/>

    <%= f.label "address_quarter_id_equals", Quarter.model_name.human(:name => "name") %>
    <%= f.collection_select("address_quarter_id_equals", address[:quarters][:options], :id, :name, {:include_blank => true, :selected => address[:quarters][:selected]}, {:id => "quarter_id"}) %>
  </div>
  <br/>

  <div id="address_street">
    <%= f.label :address_street_equals, Address.human_attribute_name("street") %>
    <%= f.text_field :address_street_equals, :style => "width: 120px;" %>
    <%= f.label :address_number_equals, Address.human_attribute_name("number") %>
    <%= f.text_field :address_number_equals, :style => "width: 30px;" %>
  </div>

<% end %>

<div class="clear"></div>

app/views/admin/addresses/_show_address.html.erb
<%= show_address(@address) if @address %>