config/routes.rb
Re::Application.routes.draw do
  root :to => "admin/contacts#index_contacts"
  #  Translate::Routes.translation_ui(map) if RAILS_ENV != "production"

    #  https://github.com/ccoenen/rails-translate
    scope '/translate' do
      match '/translate_list', :to => 'translate#index'
      match '/translate', :to => 'translate#translate'
      match '/translate_reload', :to => 'translate#reload'
    end
  
  resources :navigations do
    collection do
      get :cities
      get :quarters
      get :update_address
      get :clean_cache
      get :terms
    end
  end


  namespace :admin do

    resources :statistics do
      collection do
        get :offers_by_team
        get :do_offers_by_team
        get :full_report
        get :do_full_report
      end
    end
    
    resources :contacts do
      collection do
        get :index_clients
        get :index_contacts
        get :check
      end
      member do
        get :add
        get :tab_contact
        get :tab_projects
        get :tab_sells
        get :tab_buys
        get :show_offers
      end

      resources :buys do
        collection do
          get :tab_basic_data
          get :tab_search_results
          get :show_attachments
        end
        member do
          get :add_search_criterias
          get :buy_search_result
          get :change_buy_status
        end
        resources :buy_addresses
        resources :attachments 
        resources :search_criterias do
          member do
            get :property_type_keywords
            get :criteria_search_result
          end
        end
      end

      resources :sells do
        resources :pictures do
          collection do
            get :reload_pictures
          end
        end
      end

      resources :projects do
        resources :project_sells, :as => :sells
        member do
          get :tab_project_sells
        end
      end

    end # end contacts

    namespace :indexes do
      resources :sells do
        collection do
          get :print_sells
          get :user_offers
        end
        member do
          get :print
        end
      end

      resources :projects, :except => [:new, :create] do
        resources :project_sells, :as => :sells
        
        collection do
          get :print_projects
          get :user_projects
        end
        member do
          get :print
        end
      end

      resources :buys do
        collection do
          get :print_buys
          get :user_offers
        end
      end
    end # end indexes
      
    resources :roles
    resources :users do
      collection do
        get :help
      end
      member do
        get :activate
      end

    end

    resources :navigations do
      collection do
        get :nomenclatures
        get :guest_screen
      end
    end

    resources :countries
    resources :districts
    resources :municipalities do
      collection do
        get :load_districts
      end
    end
    
    resources :cities do
      resources :quarters do
        collection do
          get :add_multiple
          post :do_add_multiple
        end
      end
      
      collection do
        get :load_districts
        get :load_municipalities
        get :load_places
      end
    end
    
    resources :offices
    resources :teams do
      collection do
        get :update_team_users
      end


    end
    resources :spheres
    resources :contact_categories
    resources :phones
    resources :phone_types
    resources :internet_comunicators
    resources :internet_comunicator_types
    resources :exposure_types
    resources :construction_types
    resources :property_functions
    resources :property_types
    resources :heating_types
    resources :infrastructure_types
    resources :road_types
    resources :room_types
    resources :apartment_types
    resources :rooms
    resources :buildings
    resources :building_types
    resources :fence_types
    resources :property_locations
    resources :property_category_locations
    resources :keywords
    resources :validation_types
    resources :offer_types
    resources :inspections
    #resources :pictures
    resources :furnishes
    resources :sources
    resources :statuses
    resources :buy_statuses
    resources :standart_choices
    resources :project_stages
    resources :floor_types
    resources :street_types
    resources :canceled_types

    resources :index_sells do
      member do
        get :print
      end
    end

    resources :index_projects do
      member do
        get :print
        get :sells
      end
    end

    resources :addresses do
      collection do
        get :get_districts
        get :get_cities
      end
    end

  end

  match '/' => 'admin/contacts#index'
  resource :account, :controller => "users"
  resources :users
  resource :user_session
  resources :password_resets
  match '/:controller(/:action(/:id))'
end

__END__

ActionController::Routing::Routes.draw do |map|  

  
  #  Translate::Routes.translation_ui(map) if RAILS_ENV != "production"
  
  map.resources  :navigations,
    :collection => [:cities]

  map.namespace :admin do |admin|
    admin.resources :contacts,
      :collection => {
      :index_clients => :get,
      :check => :get
    },
      :member => {
      :add => :get,
      :tab_projects => :get,
      :tab_sells => :get,
      :tab_buys => :get
    } do |contact|
        
      contact.resources :buys,
        :member => {
        :add_search_criterias => :get,
        :buy_search_result => :get,
        :change_buy_status => :get,
      } do |buy|
        buy.resources :buy_addresses
        buy.resources :search_criterias,
          :member => {
          :property_type_keywords => :any,
          :criteria_search_result => :get,
        }
      end

      contact.resources :sells, :member => {:print => :get}

      contact.resources :projects, :member => {
        :print => :get,
        :tab_project_sells => :get,
      } do |project|
        project.resources :sells, :controller => "project_sells"
      end

      admin.namespace :indexes do |index|

        index.resources :sells,
          :member => {:print => :get},
          :collection => {
          :print_sells => :get,
          :user_offers => :get
        }

        index.resources :projects,
          :member => {:print => :get},
          :collection => {
          :print_projects => :get,
          :user_projects => :get
        } do |project|
          project.resources :sells
        end

        index.resources :buys,
          :member => {:print => :get},
          :collection => {
          :print_buys => :get,
          :user_offers => :get
        }
      end

    end

    admin.resources :roles

    admin.resources :users,
      :collection => {:help => :get},
      :member => {:activate => :get}

    admin.resources  :navigations, 
      :collection => [:nomenclatures, :guest_screen]

    admin.resources :countries
    admin.resources :districts

    admin.resources :municipalities,
      :collection => {:load_districts => :get}

    admin.resources :cities,
      :has_many => :quarters,
      :collection => {
      :load_municipalities => :any,
      :load_places => :any,
    }
    
    admin.resources :quarters, :collection => {
      :add_multiple => :get,
      :do_add_multiple => :post
    }
    admin.resources :offices

    admin.resources :teams, 
      :collection => {:update_team_users => :get}

    admin.resources :spheres
    admin.resources :contact_categories
    admin.resources :phones
    admin.resources :phone_types
    admin.resources :internet_comunicators
    admin.resources :internet_comunicator_types
    admin.resources :exposure_types
    admin.resources :construction_types
    admin.resources :property_functions
    admin.resources :property_types
    admin.resources :heating_types
    admin.resources :infrastructure_types
    admin.resources :road_types
    admin.resources :room_types
    admin.resources :apartment_types
    admin.resources :rooms
    admin.resources :buildings
    admin.resources :building_types
    admin.resources :fence_types
    admin.resources :property_locations
    admin.resources :property_category_locations
    admin.resources :keywords
    admin.resources :validation_types
    admin.resources :offer_types
    admin.resources :inspections
    admin.resources :pictures
    admin.resources :furnishes
    admin.resources :sources
    admin.resources :statuses
    admin.resources :buy_statuses
    admin.resources :standart_choices
    admin.resources :project_stages

    admin.resources :index_sells, 
      :except => [:new, :create],
      :member => {:print => :get}
    
    admin.resources :index_projects, 
      :except => [:new, :create],
      :member => {
      :print => :get,
      :sells => :get
    }

    admin.resources :addresses,
      :collection => {
      :update_address=> :get,
      :get_districts => :get,
      :get_cities => :get
    }
  end

  map.root :controller => "admin/contacts", :action => 'index'

  map.resource :account, :controller => "users"
  map.resources :users
  map.resource :user_session
  map.resources :password_resets
  
  # See how all your routes lay out with "rake routes"

  # Install the default routes as the lowest priority.
  # Note: These default routes make all actions in every controller accessible via GET requests. You should
  # consider removing or commenting them out if you're using named routes and resources.
  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end
#== Route Map
# Generated on 10 Dec 2010 10:57
#
#                                                     root        /(.:format)                                                                                    {:action=>"index_contacts", :controller=>"admin/contacts"}

app/controllers/admin/indexes/projects_controller.rb
class Admin::Indexes::ProjectsController < Admin::IndexesController

  load_and_authorize_resource :project, "project"

  before_filter :set_defaults

  def set_defaults
    params[:search] ||= {}
    params[:search][:active_equals] ||= "1"
    params[:search][:status_id_in] ||= Status.active.all.collect{|s| s.id}
  end
  private :set_defaults
  
  def index
    do_search
  end

  def user_projects
    
    params[:search][:user_id_equals] ||= current_user.id
   
    do_search 
    render :action => "index"
  end

  private
  def do_search conditions={}

    #    if params[:search][:status_id_equals]
    @search  = Project.search(params[:search])

    @projects = @search.relation.includes(Project::DEFAULT_INCLUDES)
    per_page = params[:per_page] ? params[:per_page].to_i : Project.per_page
    
    @projects = @projects.paginate(:page => params[:page],  :per_page => per_page )
  end

end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::BaseController


  load_resource :contact, :parent => true
  load_and_authorize_resource :project

  before_filter :belongs_to_contact, :only => [:show, :edit, :update, :destroy]


  #  def restrict_project_access
  #    unless can? :peek_offer_from_contact, @project
  #      flash[:error] = "Нямате права да извършите #{self.action_name} върху проекта"
  #      redirect_to :action => "index"
  #    end
  #  end
  
  def index
    @search  = Project.search(params[:search])
    
    @projects = @search.relation.where(:contact_id => @contact.id)
      

    @projects = @projects.paginate(
      :page => params[:page],
      :per_page => 10
    )
  end

  # Display the projects for a contact
  #  redirect_to admin_contacts_url
  #  #        @projects = current_user.projects_for_contact(@contact).paginate(:page => params[:page],
  #  #      :per_page => @@per_page)
  #  raise "трябва да се види дали не може да се централизира както е в contact.tab_projects"
  #  @search = Project.search(params[:search])
  #  @projects = @search.paginate(:page => params[:page],
  #    :include => [
  #      :translations => [],
  #      :address => [],
  #      :status => []
  #    ]
  #  )


  #  # Display mine projects
  #  def mine
  #    conditions_terms = [{"user_id" => current_user}]
  #
  #    if !params[:search] or params[:search][:status_id_equals]
  #      conditions_terms << {"status.hide_on_this_status" => false}
  #    end
  #
  #    conditions = conditions_terms.map { |c| Project.merge_conditions(c) }.join(' AND ')
  #
  #    @search  = Project.search(params[:search])
  #    @projects = @search.paginate(
  #      #      :include => {:user => [], :contact => []},
  #      :conditions => conditions,
  #      :page => params[:page]
  #    )
  #  end


  # Those bellow require contact id
  def show
    @project = Project.find(params[:id], :include =>{:user => [], :pictures => [], :documents => []})
  end

  # това се вика когато си във контакта и искаш да направиш нов проект 
  def new
    @project = @contact.projects.build
    @project.user = current_user
    @project.status = Status.default_statuses.first
    @project.build_address
  end
  
  def create
    #    assigned_attributes = merge_with_nested_attributes params[:project], :inspections, {:user_id => current_user.id}
    @project = Project.new(params[:project])
    
    if cannot?(:set_owner, @project) || @project.user.blank?
      @project.user = current_user
    end
    
    @project.contact = @contact

    if @project.save
      flash[:message] = "Успешен запис на проект #{@project.name}"
      redirect_to edit_admin_contact_project_url(
        :contact_id => @contact,
        :id => @project,
        :current_tab => params[:current_tab]
      )
    else
      render :action => 'new'
    end
  end
  
  def edit
    #    @project.documents.build
    unless current_user.id == @project.user_id.to_i
      flash[:warning] = t("Редакция като шев", :scope => [:admin])
    end
  end
  
  def update
    unless can? :set_owner, @project
      @project.user = current_user
    end

    assigned_attributes = merge_with_nested_attributes params[:project], :inspections, {:user_id => current_user.id}
    
    if @project.update_attributes(assigned_attributes)
      # && @project.injected_error.blank?
      flash[:message] = "Успешен запис на проект #{@project.name}"
      redirect_to edit_admin_contact_project_path(
        @contact,
        @project,
        :key => @contact.key
      )
    else
      #      @project.errors.add(:document, :invalid, :default  => t("attachment_removed"))
      render :action => 'edit'
    end
  end
  
  def destroy
    @project.destroy
    redirect_to admin_projects_url
  end


  def tab_project_sells
    @project = Project.find(params[:id])
    @sells = @project.sells

    render :action => "tab_project_sells", :layout => false
  end


  private
  #--------------------------------
  def belongs_to_contact
    unless @contact
      flash[:error] = "Can't display sell without contact"
      redirect_to :action => "index"
    end
    unless @contact.key == params[:key] or @contact.key
      flash[:error] = "Нямате ключ за да достъпите офертите на контакта"
    end
  end
  
end

app/views/admin/indexes/projects/_project_actions.html.erb
<%=
link_to t(:edit),
  edit_admin_contact_project_path(
  :id => project.id,
  :contact_id => project.contact.id,
  :key => project.contact.key
),
  :class => "action edit" if can? :edit, project
%>


<%=
link_to t(:show),
  admin_contact_project_path(
  project.contact,
  project
),
  :class => "action show" if can? :show, project
%>

<%#
link_to t(:print),
  admin_contact_project_path(
  project.contact,
  project
),
  :class => "action print" if can? :print, project
%>

<%=
link_to t("Клиент", :scope => [:admin, :project]),
  edit_admin_contact_path(:id => project.contact,
  :key => project.contact.key
),
  :class => "action edit_client" if can? :print, project
%>

<%=
link_to t("Oферти", :scope => [:admin, :project]),
  admin_indexes_project_sells_path(project),
  :class => "action show_project_sells" 
%>

app/views/admin/indexes/projects/_search_form.html.erb
<div class="search_form">
  <%= semantic_form_for :search, @search, :url => admin_indexes_projects_url,
    :html => {:method => :get, :class => "search_form"}  do |f| %>
    <%= hidden_field_tag "action" %>
    <fieldset>
      <div style="float:left; width: 90%">

        <div class="status_fields"
             <h4><%=  sort_link(@search, :status_id, t("status", :scope => [:admin, :project])) %></h4>
          <ul>
            <% f.check_boxes :status_id_in,
              $cache[Status].collect{|c| [c.name, c.id.to_i]}, :class => 'checkboxy' do |check| %>
              <li>
                <%= check.box %>
                <%= check.label %>
              </li>
            <% end %>
          </ul>
        </div>

        <div style="float:left;">
          <%= f.label :id_equals, sort_link(@search, :id,  t("Номер на проект", :scope => [:admin, :project])) %>
          <%= f.text_field :id_equals %>
        </div>
        <div style="float:left;">
          <%= f.label :name_contains, sort_link(@search, :id,  t("Име", :scope => [:admin, :project])) %>
          <%= f.text_field :name_contains %>
        </div>
        <div style="float:left;">
          <%= f.label :description_contains, sort_link(@search, :id,  t("Описание", :scope => [:admin, :project])) %>
          <%= f.text_field :description_contains %>
        </div>
  <%#*<div style="float:left;">%>
  <%#= raise f.object.inspect %>
  <%#= f.label :status_id_equals, sort_link(@search, :status_id, t("status", :scope => [:admin, :project])) %>
  <%#= f.select :status_id_equals, $cache[Status].collect{|c| [c.name, c.id.to_i]}, {:include_blank => true} %>
  <%#*</div>%>
        <div style="float:left;">
          <%= f.label :team_id_equals, sort_link(@search, :team_id, t("team", :scope => [:admin, :project])) %>
          <%= f.select :team_id_equals, Team.all.collect{|c| [c.name, c.id]}, {:include_blank => true} %>
        </div>



        <div style="float: left">
          <%=
          label_tag :users_id_equals,
            sort_link(@search, :user_real_name, t("available_users", :scope => [:admin, :contacts, :index_clients])
          )
        %>
          <%=
          f.select :user_id_equals,
            #current_user.my_users.collect{|user| [user.display_name(:short), user.id]},
          User.order('first_name').all.collect{|user| [user.display_name(:short), user.id]},
            {:include_blank => t(:chose)},
            {:id => "users"} if current_user.role?(:manager) or
            current_user.role?(:team_manager)
        %>
        </div>

        <div style="float:left;">
          <%=
          f.label :property_category_location_id_equals,
            sort_link(@search,
            :property_category_location_id,
            t("Локация", :scope => [:admin, :project])
          )
        %>

          <%=
          f.select :property_category_location_id_equals,
            $cache[PropertyCategoryLocation].collect{|property_category_location|
            [property_category_location.name, property_category_location.id]
          },
            {:include_blank => true}

        %>
        </div>
      </div>

      <div style="float:left;">
        <select name="per_page">
          <%= options_for_select([
              ["5", "5"],
              ["10", "10"],
              ["20", "20"],
              ["50", "50"],
              ["100", "100"],
            ],
            params[:per_page]
          ) %>
        </select>
      </div>

      <div style="float:left;">
        <%= submit_tag t(:search) %>
        <%= link_to t(:clear), nil, :class => "clear_form" %>
      </div>

  <%#= render :partial => "admin/addresses/search_form", :locals => {
  :f => f,
  :default_address => get_address_from_search(search)
  } %>

    </fieldset>
  <% end %>
</div>

app/views/admin/indexes/projects/index.html.erb
<div id="index_projects">

  
  <% title t("Списък проекти", :scope => [:admin, :project]) %>

  <%= render :partial => "search_form" %>

  <% if @projects.size > 0 %>
    <%= t("намерени резултата", :scope => [:admin, :project], :count => @projects.total_entries) %>

    <%= render :partial => "/admin/shared/project", :collection => @projects, :locals => {:actions => "/admin/indexes/projects/project_actions"} %>

    <%= will_paginate @projects  %>
  <% else %>
    <% if params[:commit] %>
      <p><%= t("Няма проекти отговарящи на търсенето", :scope => [:admin, :project]) %></p>
    <% end %>
  <% end %>
</div>

app/views/admin/indexes/projects/print.html.erb
<script type="text/javascript">
  $(document).ready(function() {
    window.print();
  })
</script>

<% title t("title", :scope => [:admin, :sells, :print]) %>

<div id="offer_sell_preview" class="ui-widget ui-widget-content ui-corner-all" style="margin: 6px;padding: 4px;display: inline-block; width: 98%">

  <div style="float: left;width: 48%;padding: 4px;margin: 4px;" class="ui-widget ui-widget-content ui-corner-all">
    <div>
      <%= t("Код",:scope => [:admin, :sells, :search_results]) %>:
      <b><%= @sell.id %></b>
    </div>
    <div>
      <%= t(:Имот, :scope => [:admin, :sells]) %> :
      <strong>
        <%= @sell.property_type.name %>
        <br/>
        <%= @sell.offer_type.name %>
      </strong>
    </div>
    <div>
      <%= t("Адрес", :scope => [:admin, :sells]) %> :
      <strong>
        <%=  can?(:peek_offer_from_contact, @sell) ? show_address(@sell.address, :long) : show_address(@sell.address, :short) %>
      </strong>
    </div>
    <br/>

    <div id="sell_keyords">
      <% @sell.keywords_sells.each do |keywords_sell| %>
        <% unless keywords_sell.value.blank? %>
          <div id="keyword">
            <%= show_keyword(@sell, keywords_sell.keyword.tag) %>
          </div>
        <% end %>
      <% end %>
      <br/>
      <div id="sell_description" class="ui-widget ui-widget-content ui-corner-all">
        <b>
          <%= Sell.human_attribute_name(:description) %> :
        </b>
        <br/>
        <%= @sell.description %>
      </div>
      <br/>
      <div id="broker_info" class="ui-widget ui-widget-content ui-corner-all">
        <%= t("Брокер",:scope => [:admin, :sells, :search_results]) %> :
        <b><%= @sell.user.display_name(:short) %></b><br/>
        <%= User.human_attribute_name(:phone) %>: <b><%= @sell.user.phone %></b><br/>
        <%= User.human_attribute_name(:mobile) %>: <b><%= @sell.user.mobile %></b><br/>
        <%= User.human_attribute_name(:email) %>: <b><%= @sell.user.email %></b>
      </div>
    </div>
  </div>

  <% if @sell.pictures.first %>
    <div style="float: left; width: 48%; padding: 4px; margin: 4px;">
      <%= image_tag @sell.pictures.first.url(:small) %>
    </div>
  <% end %>

  <% if @sell.pictures.size > 1 %>
    <div id="sell_galery" style="page-break-before: always">
      <% @sell.pictures.each do |picture| %>
        <div style="float:left; padding: 2px">
          <%= image_tag picture.url(:normal) %>
          <br/>
          <%= picture.description %>
        </div>
      <% end %>
    </div>
  <% end %>

  <div class="clear"></div>
  <br/>

</div>

app/views/admin/indexes/projects/sells.erb
<%#= index_bread_crumb %>
<%#= render :partial => "search_form" %>
<%=
  render :partial => "/admin/shared/sell", :collection => @sells, :locals => {:actions => "/admin/index_sells/sell_actions"}
%>