config/routes.rb
Re::Application.routes.draw do
  root :to => "admin/contacts#index_contacts"
  #  Translate::Routes.translation_ui(map) if RAILS_ENV != "production"

    #  https://github.com/ccoenen/rails-translate
    scope '/translate' do
      match '/translate_list', :to => 'translate#index'
      match '/translate', :to => 'translate#translate'
      match '/translate_reload', :to => 'translate#reload'
    end
  
  resources :navigations do
    collection do
      get :cities
      get :quarters
      get :update_address
      get :clean_cache
      get :terms
    end
  end


  namespace :admin do

    resources :statistics do
      collection do
        get :offers_by_team
        get :do_offers_by_team
        get :full_report
        get :do_full_report
      end
    end
    
    resources :contacts do
      collection do
        get :index_clients
        get :index_contacts
        get :check
      end
      member do
        get :add
        get :tab_contact
        get :tab_projects
        get :tab_sells
        get :tab_buys
        get :show_offers
      end

      resources :buys do
        collection do
          get :tab_basic_data
          get :tab_search_results
          get :show_attachments
        end
        member do
          get :add_search_criterias
          get :buy_search_result
          get :change_buy_status
        end
        resources :buy_addresses
        resources :attachments 
        resources :search_criterias do
          member do
            get :property_type_keywords
            get :criteria_search_result
          end
        end
      end

      resources :sells do
        resources :pictures do
          collection do
            get :reload_pictures
          end
        end
      end

      resources :projects do
        resources :project_sells, :as => :sells
        member do
          get :tab_project_sells
        end
      end

    end # end contacts

    namespace :indexes do
      resources :sells do
        collection do
          get :print_sells
          get :user_offers
        end
        member do
          get :print
        end
      end

      resources :projects, :except => [:new, :create] do
        resources :project_sells, :as => :sells
        
        collection do
          get :print_projects
          get :user_projects
        end
        member do
          get :print
        end
      end

      resources :buys do
        collection do
          get :print_buys
          get :user_offers
        end
      end
    end # end indexes
      
    resources :roles
    resources :users do
      collection do
        get :help
      end
      member do
        get :activate
      end

    end

    resources :navigations do
      collection do
        get :nomenclatures
        get :guest_screen
      end
    end

    resources :countries
    resources :districts
    resources :municipalities do
      collection do
        get :load_districts
      end
    end
    
    resources :cities do
      resources :quarters do
        collection do
          get :add_multiple
          post :do_add_multiple
        end
      end
      
      collection do
        get :load_districts
        get :load_municipalities
        get :load_places
      end
    end
    
    resources :offices
    resources :teams do
      collection do
        get :update_team_users
      end


    end
    resources :spheres
    resources :contact_categories
    resources :phones
    resources :phone_types
    resources :internet_comunicators
    resources :internet_comunicator_types
    resources :exposure_types
    resources :construction_types
    resources :property_functions
    resources :property_types
    resources :heating_types
    resources :infrastructure_types
    resources :road_types
    resources :room_types
    resources :apartment_types
    resources :rooms
    resources :buildings
    resources :building_types
    resources :fence_types
    resources :property_locations
    resources :property_category_locations
    resources :keywords
    resources :validation_types
    resources :offer_types
    resources :inspections
    #resources :pictures
    resources :furnishes
    resources :sources
    resources :statuses
    resources :buy_statuses
    resources :standart_choices
    resources :project_stages
    resources :floor_types
    resources :street_types
    resources :canceled_types

    resources :index_sells do
      member do
        get :print
      end
    end

    resources :index_projects do
      member do
        get :print
        get :sells
      end
    end

    resources :addresses do
      collection do
        get :get_districts
        get :get_cities
      end
    end

  end

  match '/' => 'admin/contacts#index'
  resource :account, :controller => "users"
  resources :users
  resource :user_session
  resources :password_resets
  match '/:controller(/:action(/:id))'
end

__END__

ActionController::Routing::Routes.draw do |map|  

  
  #  Translate::Routes.translation_ui(map) if RAILS_ENV != "production"
  
  map.resources  :navigations,
    :collection => [:cities]

  map.namespace :admin do |admin|
    admin.resources :contacts,
      :collection => {
      :index_clients => :get,
      :check => :get
    },
      :member => {
      :add => :get,
      :tab_projects => :get,
      :tab_sells => :get,
      :tab_buys => :get
    } do |contact|
        
      contact.resources :buys,
        :member => {
        :add_search_criterias => :get,
        :buy_search_result => :get,
        :change_buy_status => :get,
      } do |buy|
        buy.resources :buy_addresses
        buy.resources :search_criterias,
          :member => {
          :property_type_keywords => :any,
          :criteria_search_result => :get,
        }
      end

      contact.resources :sells, :member => {:print => :get}

      contact.resources :projects, :member => {
        :print => :get,
        :tab_project_sells => :get,
      } do |project|
        project.resources :sells, :controller => "project_sells"
      end

      admin.namespace :indexes do |index|

        index.resources :sells,
          :member => {:print => :get},
          :collection => {
          :print_sells => :get,
          :user_offers => :get
        }

        index.resources :projects,
          :member => {:print => :get},
          :collection => {
          :print_projects => :get,
          :user_projects => :get
        } do |project|
          project.resources :sells
        end

        index.resources :buys,
          :member => {:print => :get},
          :collection => {
          :print_buys => :get,
          :user_offers => :get
        }
      end

    end

    admin.resources :roles

    admin.resources :users,
      :collection => {:help => :get},
      :member => {:activate => :get}

    admin.resources  :navigations, 
      :collection => [:nomenclatures, :guest_screen]

    admin.resources :countries
    admin.resources :districts

    admin.resources :municipalities,
      :collection => {:load_districts => :get}

    admin.resources :cities,
      :has_many => :quarters,
      :collection => {
      :load_municipalities => :any,
      :load_places => :any,
    }
    
    admin.resources :quarters, :collection => {
      :add_multiple => :get,
      :do_add_multiple => :post
    }
    admin.resources :offices

    admin.resources :teams, 
      :collection => {:update_team_users => :get}

    admin.resources :spheres
    admin.resources :contact_categories
    admin.resources :phones
    admin.resources :phone_types
    admin.resources :internet_comunicators
    admin.resources :internet_comunicator_types
    admin.resources :exposure_types
    admin.resources :construction_types
    admin.resources :property_functions
    admin.resources :property_types
    admin.resources :heating_types
    admin.resources :infrastructure_types
    admin.resources :road_types
    admin.resources :room_types
    admin.resources :apartment_types
    admin.resources :rooms
    admin.resources :buildings
    admin.resources :building_types
    admin.resources :fence_types
    admin.resources :property_locations
    admin.resources :property_category_locations
    admin.resources :keywords
    admin.resources :validation_types
    admin.resources :offer_types
    admin.resources :inspections
    admin.resources :pictures
    admin.resources :furnishes
    admin.resources :sources
    admin.resources :statuses
    admin.resources :buy_statuses
    admin.resources :standart_choices
    admin.resources :project_stages

    admin.resources :index_sells, 
      :except => [:new, :create],
      :member => {:print => :get}
    
    admin.resources :index_projects, 
      :except => [:new, :create],
      :member => {
      :print => :get,
      :sells => :get
    }

    admin.resources :addresses,
      :collection => {
      :update_address=> :get,
      :get_districts => :get,
      :get_cities => :get
    }
  end

  map.root :controller => "admin/contacts", :action => 'index'

  map.resource :account, :controller => "users"
  map.resources :users
  map.resource :user_session
  map.resources :password_resets
  
  # See how all your routes lay out with "rake routes"

  # Install the default routes as the lowest priority.
  # Note: These default routes make all actions in every controller accessible via GET requests. You should
  # consider removing or commenting them out if you're using named routes and resources.
  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end
#== Route Map
# Generated on 10 Dec 2010 10:57
#
#                                                     root        /(.:format)                                                                                    {:action=>"index_contacts", :controller=>"admin/contacts"}

app/controllers/admin/indexes/projects_controller.rb
class Admin::Indexes::ProjectsController < Admin::IndexesController

  load_and_authorize_resource :project, "project"

  before_filter :set_defaults

  def set_defaults
    params[:search] ||= {}
    params[:search][:active_equals] ||= "1"
    params[:search][:status_id_in] ||= Status.active.all.collect{|s| s.id}
  end
  private :set_defaults
  
  def index
    do_search
  end

  def user_projects
    
    params[:search][:user_id_equals] ||= current_user.id
   
    do_search 
    render :action => "index"
  end

  private
  def do_search conditions={}

    #    if params[:search][:status_id_equals]
    @search  = Project.search(params[:search])

    @projects = @search.relation.includes(Project::DEFAULT_INCLUDES)
    per_page = params[:per_page] ? params[:per_page].to_i : Project.per_page
    
    @projects = @projects.paginate(:page => params[:page],  :per_page => per_page )
  end

end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::BaseController


  load_resource :contact, :parent => true
  load_and_authorize_resource :project

  before_filter :belongs_to_contact, :only => [:show, :edit, :update, :destroy]


  #  def restrict_project_access
  #    unless can? :peek_offer_from_contact, @project
  #      flash[:error] = "Нямате права да извършите #{self.action_name} върху проекта"
  #      redirect_to :action => "index"
  #    end
  #  end
  
  def index
    @search  = Project.search(params[:search])
    
    @projects = @search.relation.where(:contact_id => @contact.id)
      

    @projects = @projects.paginate(
      :page => params[:page],
      :per_page => 10
    )
  end

  # Display the projects for a contact
  #  redirect_to admin_contacts_url
  #  #        @projects = current_user.projects_for_contact(@contact).paginate(:page => params[:page],
  #  #      :per_page => @@per_page)
  #  raise "трябва да се види дали не може да се централизира както е в contact.tab_projects"
  #  @search = Project.search(params[:search])
  #  @projects = @search.paginate(:page => params[:page],
  #    :include => [
  #      :translations => [],
  #      :address => [],
  #      :status => []
  #    ]
  #  )


  #  # Display mine projects
  #  def mine
  #    conditions_terms = [{"user_id" => current_user}]
  #
  #    if !params[:search] or params[:search][:status_id_equals]
  #      conditions_terms << {"status.hide_on_this_status" => false}
  #    end
  #
  #    conditions = conditions_terms.map { |c| Project.merge_conditions(c) }.join(' AND ')
  #
  #    @search  = Project.search(params[:search])
  #    @projects = @search.paginate(
  #      #      :include => {:user => [], :contact => []},
  #      :conditions => conditions,
  #      :page => params[:page]
  #    )
  #  end


  # Those bellow require contact id
  def show
    @project = Project.find(params[:id], :include =>{:user => [], :pictures => [], :documents => []})
  end

  # това се вика когато си във контакта и искаш да направиш нов проект 
  def new
    @project = @contact.projects.build
    @project.user = current_user
    @project.status = Status.default_statuses.first
    @project.build_address
  end
  
  def create
    #    assigned_attributes = merge_with_nested_attributes params[:project], :inspections, {:user_id => current_user.id}
    @project = Project.new(params[:project])
    
    if cannot?(:set_owner, @project) || @project.user.blank?
      @project.user = current_user
    end
    
    @project.contact = @contact

    if @project.save
      flash[:message] = "Успешен запис на проект #{@project.name}"
      redirect_to edit_admin_contact_project_url(
        :contact_id => @contact,
        :id => @project,
        :current_tab => params[:current_tab]
      )
    else
      render :action => 'new'
    end
  end
  
  def edit
    #    @project.documents.build
    unless current_user.id == @project.user_id.to_i
      flash[:warning] = t("Редакция като шев", :scope => [:admin])
    end
  end
  
  def update
    unless can? :set_owner, @project
      @project.user = current_user
    end

    assigned_attributes = merge_with_nested_attributes params[:project], :inspections, {:user_id => current_user.id}
    
    if @project.update_attributes(assigned_attributes)
      # && @project.injected_error.blank?
      flash[:message] = "Успешен запис на проект #{@project.name}"
      redirect_to edit_admin_contact_project_path(
        @contact,
        @project,
        :key => @contact.key
      )
    else
      #      @project.errors.add(:document, :invalid, :default  => t("attachment_removed"))
      render :action => 'edit'
    end
  end
  
  def destroy
    @project.destroy
    redirect_to admin_projects_url
  end


  def tab_project_sells
    @project = Project.find(params[:id])
    @sells = @project.sells

    render :action => "tab_project_sells", :layout => false
  end


  private
  #--------------------------------
  def belongs_to_contact
    unless @contact
      flash[:error] = "Can't display sell without contact"
      redirect_to :action => "index"
    end
    unless @contact.key == params[:key] or @contact.key
      flash[:error] = "Нямате ключ за да достъпите офертите на контакта"
    end
  end
  
end

app/views/admin/projects/_basic_data.html.erb
<h1><%= t("Проект", :project => project.name, :scope => [:admin, :project]) %></h1>
<p>
  <strong><%= t("status", :scope => [:activerecord, :attributes, :project]) %>:</strong>
  <%=h project.status.name %><br/>
  <strong><%= t("source", :scope => [:activerecord, :attributes, :project]) %>:</strong>
  <%=h project.source.name %>
</p>

<%= render :partial => '/admin/shared/show_owners', :locals => {:object => project} %>

<p>
  <strong><%= t("furnish", :scope => [:activerecord, :attributes, :project]) %>:</strong>
  <%=h project.furnish.name rescue "---"%><br/>
  <strong><%= t("source_value", :scope => [:activerecord, :attributes, :project]) %>:</strong>
  <%=h project.source_value %><br/>

  <strong><%= t("contact_person", :scope => [:activerecord, :attributes, :project]) %>:</strong>
  <%=h project.contact_person %><br/>
  <strong><%= t("contact_person_phone", :scope => [:activerecord, :attributes, :project]) %>:</strong>

  <%=h project.contact_person_phone rescue '---' %><br/>
  <strong><%= t("website", :scope => [:activerecord, :attributes, :project]) %>:</strong>
  <%= if project.website =~ /^http:/
    link_to(project.website, project.website, :target => "_blank")
  elsif project.website =~ /^www/
    link_to(project.website, "http://#{project.website}", :target => "_blank")
  else
    project.website
  end
%><br/>
  <strong><%= t("start_date", :scope => [:activerecord, :attributes, :project]) %>:</strong>
  <%=h project.start_date rescue '---' %><br/>
  <strong><%= t("finish_date", :scope => [:activerecord, :attributes, :project]) %>:</strong>
  <%=h project.finish_date %><br/>
  <strong><%= t("reference_point", :scope => [:activerecord, :attributes, :project]) %>:</strong>
  <%=h project.reference_point %><br/>
</p>
<p>
  <strong><%= t("adres", :scope => [:activerecord, :attributes, :project]) %>:</strong>
  <%=
  if can?(:peek_offer_from_contact, project) and project.address
    show_address(project.address, :full_array).join("<br/>").html_safe
  else
    show_address(project.address, :short)
  end
%>
</p>
<p>
  <strong><%= t("property_category_location", :scope => [:activerecord, :attributes, :project]) %>:</strong>
  <%=h project.property_category_location.name  %><br/>
  <strong><%= t("managment_fee", :scope => [:activerecord, :attributes, :project]) %>:</strong>
  <%=h project.managment_fee %><br/>
  <strong><%= t("discount", :scope => [:activerecord, :attributes, :project]) %>:</strong>
  <%=h project.discount %><br/>
  <strong><%= t("brokerage", :scope => [:activerecord, :attributes, :project]) %>:</strong>
  <%=h project.brokerage  %><br/>
  <strong><%= t("description", :scope => [:activerecord, :attributes, :project]) %>:</strong>
  <%=h project.description %>
</p>



<% unless project.additional_description.blank? %>
  <p>
    <strong><%= t("additional_description", :scope => [:activerecord, :attributes, :project]) %>:</strong>
    <%=h project.additional_description %>
  </p>
<% end %>

app/views/admin/projects/_form.html.erb
<div id="project">
  <script type="text/javascript">
    $(document).ready(function() {


      // The tabs http://jqueryui.com/demos/tabs/#method-widget
      var $tabs = $('#project_tabs').tabs(
      { cookie: { expires: 7, name: "project_tabs_<%= dom_id(@project) %> " },
        ajaxOptions: { async: false }
      });



      /*
      var $tabs = $('#project_tabs').tabs();
      var $selected = $tabs.tabs('select', <%= params[:current_tab] || 0 %> );

      $('.ui-tabs-selected').click(
      function() {
        if ($(this) != $selected) {
          $selected.addClass('ui-tabs-hide');
          $(this).removeClass('ui-tabs-hide');
          $selected = $(this);
        }
      })

      $('form').submit(function() {
        var selected = $tabs.tabs('option', 'selected'); 
        $('#current_tab').val(selected);
      });
       */
    });
  </script>

  <%= semantic_form_for [:admin, @contact, @project], :html => {:multipart => true}  do |project_form| %>
    <%= project_form.error_messages %>


    <%= tabs_for(:id => :project_tabs) do |tab| %>

      <% tab.create('basic_info', t('tab:Информация за проекта', :scope => [:admin, :project])) do %>
        <%= project_form.inputs t(:"За проекта", :scope => [:admin, :project]), :id => "phone_form" do %>
          <div style="clear:both">
            <%= project_form.input :active, :as => :hidden, :value => true %>
          </div>

          <%= project_form.input :name %>

          <% if can? :set_owner, @project %>
            <%= project_form.input :user_id,
              :required => true,
              :collection => current_user.my_users.collect{|chield| [chield.display_name, chield.id]},
              :include_blank => current_user.root?,
              :label => t("Консултант", :scope => [:admin, :project])
          %>
          <% else %>
            <%= content_tag :li, @user.try(:parent).try(:email) %>
          <% end %>

          <%=
          project_form.input :status_id,
            :required => true,
            :as => :select,
            :collection => $cache['Status'].collect{|status| [status.name, status.id]},
            :include_blank => false
        %>
          <%= project_form.input :project_stage %>
          <%= project_form.input :source %>
          <%= project_form.input :source_value %>
          <%= project_form.input :property_category_location %>
          <%= project_form.input :reference_point %>
          <%= project_form.input :contact_person %>
          <%= project_form.input :contact_person_phone %>
          <%= project_form.input :website %>
          <%= project_form.input :start_date, :as => :calendar, :allow_nil => true %>
          <%= project_form.input :finish_date, :as => :calendar, :allow_nil => true %>
          <%= project_form.input :furnish %>
          <%= project_form.input :managment_fee%>
          <%= project_form.input :discount %>
          <%= project_form.input :brokerage %>
          <div class="clear"></div>
          <%= project_form.input :description, :as => :text, :input_html => {:style => "width: 570px"} %>

          <%= project_form.semantic_fields_for :address do |address| %>
            <%= render :partial => "admin/addresses/address_form", :locals => {:f => address} %>
            <div class="clear"></div>
          <% end %>

        <% end %>

        <%= project_form.buttons do %>
          <%= project_form.commit_button  :button_html => { :class => "large" } %>
        <% end %>

      <% end %>

      <% unless @project.new_record? %>
        <%
        tab.create(tab_project_sells_admin_contact_project_url(:id => @project.id, :contact_id => @contact.id, :key => @contact.key, :current_tab => 0),
          t("Оферти към проекта", :scope => [:admin, :project])) {} unless @project.new_record?
      %>

        <% tab.create('inspections', t('tab:Огледи', :scope => [:admin, :project])) do %>
          <%= project_form.inputs t(:"Огледи", :scope => [:admin, :project]), :id => "inspection_forms" do %>
            <%= nested_edit project_form, :inspections, "/admin/shared/inspection_fields",  t("Добави оглед", :scope => [:partials, :inspections]), Proc.new{|item| !item.new_record? }  %>
          <% end %>
          <%= project_form.buttons do %>
            <%= project_form.commit_button  :button_html => { :class => "large" } %>
          <% end %>
        <% end %>

        <% tab.create('pictures', t('tab:Галерия', :scope => [:admin, :project])) do %>
          <%= project_form.inputs t(:"Галерия на проекта", :scope => [:admin, :project]), :id => "picture_forms" do %>
            <%= nested_edit project_form, :pictures, "/admin/shared/picture_fields", t(:"Добави снимка", :scope => [:partials,  :pictures]), Proc.new{|item| item.picture.file? } %>
          <% end %>
          <%= project_form.buttons do %>
            <%= project_form.commit_button  :button_html => { :class => "large" } %>
          <% end %>
        <% end %>

        <% tab.create('documents', t('tab:Документи', :scope => [:admin, :project])) do %>
          <%= project_form.inputs t(:"Документи на проекта", :scope => [:admin, :project]), :id => "document_forms" do %>
            <%= nested_edit project_form, :documents, "/admin/shared/document_fields", t(:"Добави файл", :scope => [:partials, :documents]), Proc.new{|item| item.document.file? }  %>
          <% end %>
          <%= project_form.buttons do %>
            <%= project_form.commit_button  :button_html => { :class => "large" } %>
          <% end %>
        <% end %>
      <% end %>
    <% end %>





  <% end %>

  <%= render :partial => "/admin/shared/timestamps", :locals => {:object => @project} %>
</div>

app/views/admin/projects/_project_actions.html.erb
<%=
    link_to(t(:edit),
    edit_admin_contact_project_path(
      contact,
        project,
        :key => contact.key
    ),
    :class => "action edit") if can? :edit, project
%>
<%=
    link_to(t(:show),
    admin_contact_project_path(
      contact,
        project
    ),
    :class => "action show") if can? :show, project
%>

app/views/admin/projects/_project_sell_fields.html.erb
<fieldset class="project_sell">
  <legend><%= t("ProjectSell", :scope =>[:partials, :projects]) %></legend>

  <div id="dialog_<%= f.object_id.abs %>" title="<%= t("Изтриване", :scope => [:partials, :pictures])  %> <%= f.object.name %>" style="display: none">
    <p>
      <span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 30px 0;"></span>
      <%= t("Изтриване", :scope => [:partials, :projects])  %> <%= f.object.name %><br />
      <%= t("Are you sure?") %>
    </p>
  </div>

  <ul class="item_preview" >
    <li>  

      <%= remove_link(f) %>

      <% if has_expanded_preview  %>
        <%= link_to image_tag("edit.png", :class => "icon"), "#", :id => "#{f.object_id.abs}", :class => "toggle_item_form" %>

        <!-- Put the preview fields here -->

      <%= h f.object.offer_type.name %><br/>

    <% else %>
      <%= t("Изтриване", :scope => [:partials, :pictures]) %>
    <% end %>
    </li>
  </ul>

  <ul class="item_form" <%= f.object.new_record? ? "" : 'style="display:none"' %> >
    <%=
      f.input :project_unit,
        :wrapper_html => {:style => "display: inline;", :class => "fieldset_#{dom_id(f.object)}"},
        :input_html => {:style => "width: 120px; display: inline;margin-right: 10px;"}
    %>
  
  </ul>

</fieldset>

app/views/admin/projects/_search_results.html.erb
<script type="text/javascript">
  $(document).ready(function() {
    $('a.show').click(function(){
      window.open(this.href);
      return false;
    });

    $(".pagination a").click(function() {
      $("#ui-tabs-32").load(this.href, function() {
        // fire tabload event
        $('#contact_tabs').trigger('tabsload')
      });
      return false;
    });
    //http://stackoverflow.com/questions/168963/stop-jquery-load-response-from-being-cached
  });
</script>

<div id="project_search_results">
  <% if @projects.size == 0 %>
    <h2>
      <%= t("Няма налични проекти",  :scope => [:admin, :contacts]) %>
    </h2>
  <% else %>
    <%=
      render :partial => "/admin/shared/project",
        :locals => {
          :contact => @contact,
          :actions => "/admin/projects/project_actions"
        },
        :collection => @projects
    %>
  <% end %>
</div>

<%= will_paginate @projects  %>

app/views/admin/projects/edit.html.erb
<% title t("Edit Project", :scope => [:admin, :project], :name => @project.name) %>

<%= breadcrumbs_for_contact(@contact, :contact_projects_index, @project) %>

<%= render :partial => 'form' %>

app/views/admin/projects/index.html.erb
<% title t("Проекти на", :scope => [:admin, :project], :contact => @contact.name) %>

<%= breadcrumbs_for_contact(@contact, :contact_projects_index) %>


<%= link_to t("Add Project", :scope => [:admin, :project]),
  new_admin_contact_project_path(:contact => @contact),
  :class => "fg-button fg-button-icon-right ui-widget ui-state-default ui-corner-all" %>
<div style="clear: both;">
</div>

<h2><%= t("Всичко проекти", :scope => [:admin, :project], :number => @projects.total_entries) %></h2>

<%#= render :partial => 'search_form', :locals => {:search => @search} %>

<div id="project_search_results">
  <% if @projects.size == 0 %>
    <h2>
      <%= t("Няма налични проекти",  :scope => [:admin, :contacts]) %>
    </h2>
  <% else %>
    <%= 
      render :partial => "/admin/shared/project",
        :collection => @projects,
        :locals => {
          :contact => @contact, 
          :actions => "/admin/projects/project_actions"
        }
    %>
    <%= will_paginate @projects %>
  <% end %>
</div>

app/views/admin/projects/index_delme.html.erb
<% title t("Projects", :scope => [:admin, :project]) %>

<%= render :partial => 'search_form', :locals => {:search => @search} %>

<%= render :partial => 'search_results', :locals => {:projects => @projects} %>

<%= will_paginate @projects %>

app/views/admin/projects/mine.delme.html.erb.erb
<% title t("Мойте проекти", :scope => [:admin, :project], :user => current_user.display_name) %>

<%= render :partial => 'search_form', :locals => {:search => @search} %>

<%= render :partial => 'contacts', :locals => {:projects => @projects} %>

<%= will_paginate @projects %>

app/views/admin/projects/show.html.erb
<% title t("Проект", :project => @project.name, :scope => [:admin, :project]) %>

<%= breadcrumbs_for_contact(@project.contact, :contact_projects_index, @project) %>

<%= render :partial => '/admin/projects/basic_data', :locals => {:project => @project} %>
<%= render :partial => '/admin/shared/documents_list', :locals => {:object => @project} %>


<% if @project.pictures.size > 0 %>
  <h2><%= t("Галерия на проекта", :scope => [:admin, :project]) %></h2>
  <div id="sell_galery" >
    <% @project.pictures.each do |picture| %>
      <div style="float:left; padding: 2px" style="page-break-before: always">
        <%= image_tag picture.url(:normal) %>
        <br/>
        <%= picture.description %>
      </div>
    <% end %>
  </div>
<% end %>

<p style="clear: both">
  <%= link_to t("View All", :scope => [:admin, :project]), admin_contact_projects_path(:contact_id => @contact) %>
  <%= link_to t("Edit", :scope => [:admin, :project]),
    edit_admin_contact_project_path(:contact_id => @contact, :key => @contact.key, :id => @project) if can? :edit, @project %>
</p>

app/views/admin/projects/tab_project_sells.html.erb
<script type="text/javascript">
  $(document).ready(function() {
    $(function() {
      $(".pagination a").click(function() {
        $("#ui-tabs-19").load(this.href, function() {
          // fire tabload event
          $('#contact_tabs').trigger('tabsload')
        });
        return false;
      });
    });
  })
</script>

<div style="padding: 0 1px 0 0;">
  <iframe src="<%= admin_contact_project_sells_url(
      :contact_id => @contact.id, :project_id => @project) %>"
          id="sells_iframe"
          frameborder="0"
          allowtransparency="true"
          style="border:0;overflow:auto;"
          scrolling="no"
          name="sells_frame" width="100%" height="658px"
          >
  </iframe>
</div>