config/routes.rb
Re::Application.routes.draw do
  root :to => "admin/contacts#index_contacts"
  #  Translate::Routes.translation_ui(map) if RAILS_ENV != "production"

    #  https://github.com/ccoenen/rails-translate
    scope '/translate' do
      match '/translate_list', :to => 'translate#index'
      match '/translate', :to => 'translate#translate'
      match '/translate_reload', :to => 'translate#reload'
    end
  
  resources :navigations do
    collection do
      get :cities
      get :quarters
      get :update_address
      get :clean_cache
      get :terms
    end
  end


  namespace :admin do

    resources :statistics do
      collection do
        get :offers_by_team
        get :do_offers_by_team
        get :full_report
        get :do_full_report
      end
    end
    
    resources :contacts do
      collection do
        get :index_clients
        get :index_contacts
        get :check
      end
      member do
        get :add
        get :tab_contact
        get :tab_projects
        get :tab_sells
        get :tab_buys
        get :show_offers
      end

      resources :buys do
        collection do
          get :tab_basic_data
          get :tab_search_results
          get :show_attachments
        end
        member do
          get :add_search_criterias
          get :buy_search_result
          get :change_buy_status
        end
        resources :buy_addresses
        resources :attachments 
        resources :search_criterias do
          member do
            get :property_type_keywords
            get :criteria_search_result
          end
        end
      end

      resources :sells do
        resources :pictures do
          collection do
            get :reload_pictures
          end
        end
      end

      resources :projects do
        resources :project_sells, :as => :sells
        member do
          get :tab_project_sells
        end
      end

    end # end contacts

    namespace :indexes do
      resources :sells do
        collection do
          get :print_sells
          get :user_offers
        end
        member do
          get :print
        end
      end

      resources :projects, :except => [:new, :create] do
        resources :project_sells, :as => :sells
        
        collection do
          get :print_projects
          get :user_projects
        end
        member do
          get :print
        end
      end

      resources :buys do
        collection do
          get :print_buys
          get :user_offers
        end
      end
    end # end indexes
      
    resources :roles
    resources :users do
      collection do
        get :help
      end
      member do
        get :activate
      end

    end

    resources :navigations do
      collection do
        get :nomenclatures
        get :guest_screen
      end
    end

    resources :countries
    resources :districts
    resources :municipalities do
      collection do
        get :load_districts
      end
    end
    
    resources :cities do
      resources :quarters do
        collection do
          get :add_multiple
          post :do_add_multiple
        end
      end
      
      collection do
        get :load_districts
        get :load_municipalities
        get :load_places
      end
    end
    
    resources :offices
    resources :teams do
      collection do
        get :update_team_users
      end


    end
    resources :spheres
    resources :contact_categories
    resources :phones
    resources :phone_types
    resources :internet_comunicators
    resources :internet_comunicator_types
    resources :exposure_types
    resources :construction_types
    resources :property_functions
    resources :property_types
    resources :heating_types
    resources :infrastructure_types
    resources :road_types
    resources :room_types
    resources :apartment_types
    resources :rooms
    resources :buildings
    resources :building_types
    resources :fence_types
    resources :property_locations
    resources :property_category_locations
    resources :keywords
    resources :validation_types
    resources :offer_types
    resources :inspections
    #resources :pictures
    resources :furnishes
    resources :sources
    resources :statuses
    resources :buy_statuses
    resources :standart_choices
    resources :project_stages
    resources :floor_types
    resources :street_types
    resources :canceled_types

    resources :index_sells do
      member do
        get :print
      end
    end

    resources :index_projects do
      member do
        get :print
        get :sells
      end
    end

    resources :addresses do
      collection do
        get :get_districts
        get :get_cities
      end
    end

  end

  match '/' => 'admin/contacts#index'
  resource :account, :controller => "users"
  resources :users
  resource :user_session
  resources :password_resets
  match '/:controller(/:action(/:id))'
end

__END__

ActionController::Routing::Routes.draw do |map|  

  
  #  Translate::Routes.translation_ui(map) if RAILS_ENV != "production"
  
  map.resources  :navigations,
    :collection => [:cities]

  map.namespace :admin do |admin|
    admin.resources :contacts,
      :collection => {
      :index_clients => :get,
      :check => :get
    },
      :member => {
      :add => :get,
      :tab_projects => :get,
      :tab_sells => :get,
      :tab_buys => :get
    } do |contact|
        
      contact.resources :buys,
        :member => {
        :add_search_criterias => :get,
        :buy_search_result => :get,
        :change_buy_status => :get,
      } do |buy|
        buy.resources :buy_addresses
        buy.resources :search_criterias,
          :member => {
          :property_type_keywords => :any,
          :criteria_search_result => :get,
        }
      end

      contact.resources :sells, :member => {:print => :get}

      contact.resources :projects, :member => {
        :print => :get,
        :tab_project_sells => :get,
      } do |project|
        project.resources :sells, :controller => "project_sells"
      end

      admin.namespace :indexes do |index|

        index.resources :sells,
          :member => {:print => :get},
          :collection => {
          :print_sells => :get,
          :user_offers => :get
        }

        index.resources :projects,
          :member => {:print => :get},
          :collection => {
          :print_projects => :get,
          :user_projects => :get
        } do |project|
          project.resources :sells
        end

        index.resources :buys,
          :member => {:print => :get},
          :collection => {
          :print_buys => :get,
          :user_offers => :get
        }
      end

    end

    admin.resources :roles

    admin.resources :users,
      :collection => {:help => :get},
      :member => {:activate => :get}

    admin.resources  :navigations, 
      :collection => [:nomenclatures, :guest_screen]

    admin.resources :countries
    admin.resources :districts

    admin.resources :municipalities,
      :collection => {:load_districts => :get}

    admin.resources :cities,
      :has_many => :quarters,
      :collection => {
      :load_municipalities => :any,
      :load_places => :any,
    }
    
    admin.resources :quarters, :collection => {
      :add_multiple => :get,
      :do_add_multiple => :post
    }
    admin.resources :offices

    admin.resources :teams, 
      :collection => {:update_team_users => :get}

    admin.resources :spheres
    admin.resources :contact_categories
    admin.resources :phones
    admin.resources :phone_types
    admin.resources :internet_comunicators
    admin.resources :internet_comunicator_types
    admin.resources :exposure_types
    admin.resources :construction_types
    admin.resources :property_functions
    admin.resources :property_types
    admin.resources :heating_types
    admin.resources :infrastructure_types
    admin.resources :road_types
    admin.resources :room_types
    admin.resources :apartment_types
    admin.resources :rooms
    admin.resources :buildings
    admin.resources :building_types
    admin.resources :fence_types
    admin.resources :property_locations
    admin.resources :property_category_locations
    admin.resources :keywords
    admin.resources :validation_types
    admin.resources :offer_types
    admin.resources :inspections
    admin.resources :pictures
    admin.resources :furnishes
    admin.resources :sources
    admin.resources :statuses
    admin.resources :buy_statuses
    admin.resources :standart_choices
    admin.resources :project_stages

    admin.resources :index_sells, 
      :except => [:new, :create],
      :member => {:print => :get}
    
    admin.resources :index_projects, 
      :except => [:new, :create],
      :member => {
      :print => :get,
      :sells => :get
    }

    admin.resources :addresses,
      :collection => {
      :update_address=> :get,
      :get_districts => :get,
      :get_cities => :get
    }
  end

  map.root :controller => "admin/contacts", :action => 'index'

  map.resource :account, :controller => "users"
  map.resources :users
  map.resource :user_session
  map.resources :password_resets
  
  # See how all your routes lay out with "rake routes"

  # Install the default routes as the lowest priority.
  # Note: These default routes make all actions in every controller accessible via GET requests. You should
  # consider removing or commenting them out if you're using named routes and resources.
  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end
#== Route Map
# Generated on 10 Dec 2010 10:57
#
#                                                     root        /(.:format)                                                                                    {:action=>"index_contacts", :controller=>"admin/contacts"}

app/controllers/admin/indexes/sells_controller.rb
require 'will_paginate/array'

class Admin::Indexes::SellsController < Admin::IndexesController

  load_and_authorize_resource :sell, "sell", :class => Sell

  @@per_page = 5

  #  load_and_authorize_resource
  def default_url_options(options={})
    options.merge(:offer_type_id => params[:offer_type_id])
  end 

  def index
    @sells = get_sells
  end

  def user_offers
    @sells = get_sells :user_id => current_user.id
    
    render :action => "index"
  end

  private
  def get_sells init_params={}
    if params[:commit]
      if params[:sell_search]
        # параметрите от търсенето са значещи
        if params[:sell_search][:number].blank?
          search_params =  params[:sell_search]
        else
          search_params = {}
          search_params[:number] = params[:sell_search][:number]
        end
      else
        # взимаме параметрите по-подразбиране за търсенето
        search_params = init_params
        search_params[:status_ids] = Status.active.all.collect{|s| s.id}
      end

      @sell_search = SellSearch.new(search_params)

      if !search_params[:status_ids].blank? and !search_params[:number].blank?
        flash[:notice] = t("number_or_status_warning", :scope => [:admin, :sell_search])
      end

      per_page = params[:per_page] ? params[:per_page].to_i : @@per_page
      offset = params[:page] ? ((params[:page].to_i - 1) * per_page) : 0

      
      @sells = @sell_search.sell_documents.paginate(:page => params[:page], :per_page => params[:per_page])
    else
      @sell_search = SellSearch.new(:offer_type_id => params[:offer_type_id])
      @sells = []
    end

  end

end

app/controllers/admin/sells_controller.rb
class Admin::SellsController < Admin::BaseController

  load_resource :contact, :parent => true
  load_and_authorize_resource :sell

  before_filter :belongs_to_contact, :only => [:show, :edit, :update, :destroy] 

  def index
    per_page = 15
    offset = params[:page] ? ((params[:page].to_i - 1) * per_page) : 0
    @sells = current_user.sells_for_contact(@contact).
      order_by([[:updated_at, :desc], [:created_at_at, :desc]]).
      skip(offset).
      limit(per_page).
      paginate
  end

  def show
    @sell = @contact.sells.find(params[:id],
      :include => {
        :property_type => [:keywords => :keywords_property_types],
        :inspections => {:user => []},
      }      
    )
  end
  
  def new
    #      @keywords = Keyword.all(:conditions =>
    #          [
    #          "keywords_property_types.property_type_id=:property_type_id",
    #          {:property_type_id=> params[:property_type_id]}
    #        ],
    #        :include => [:keywords_property_types],
    #        :order => "keywords_property_types.position"
    #      )

    @keywords = Keyword.where([
        "keywords_property_types.property_type_id=:property_type_id",
        {:property_type_id=> params[:property_type_id]}
      ]).includes(:keywords_property_types, :translations).
      order("keywords_property_types.position")
      
    @sell = @contact.sells.build({
        :property_type_id => params[:property_type_id],
        :offer_type_id => params[:offer_type_id].to_i,
        :user_id => current_user.id
      })

    @sell.build_address
      
    @keywords.each do |keyword|
      @sell.keywords_sells.build(
        :keyword => keyword
      )
    end
  end
  
  def create
    @sell = @contact.sells.build(params[:sell])
    if @sell.save      
      #      redirect_to edit_admin_contact_path(:id => @sell.contact.id, :key => @sell.contact.key)
      flash[:notice] = t("Успешно записана", :scope => [:admin, :sells])
      redirect_to edit_admin_contact_sell_path(:id => @sell.id, :key => @sell.contact.key, :contact_id => @sell.contact.id)
    else
      render :action => 'new'
    end
  end
  
  def edit
    @sell = Sell.where(:id => params[:id]).where("keywords_sells.sell_id" => params[:id]).
      includes(:translations => [],
      :keywords_sells => {:keyword => [:validation_types]}, # :translations
      :offer_type => [:translations],
      :status => [:translations],
      :pictures => [:translations],
      :documents => [:translations],
      :inspections => [:translations],
      :property_category_location => [:translations],
      :property_type => [:translations]).
      limit(1).
      first

    @pictures = @sell.pictures

    availble_keywords = Keyword.where("keywords_property_types.property_type_id" => @sell.property_type.id).
      includes(:keywords_property_types, :translations).
      all()
    sell_keywords = @sell.keywords

    unless availble_keywords.count == sell_keywords.count
      missing_keywords = availble_keywords - sell_keywords
      missing_keywords.each do |missing_keyword|
        @sell.keywords_sells.build(
          :keyword => missing_keyword
        )
      end
    end
    
    unless current_user.id == @sell.user_id.to_i
      flash[:warning] = t("Редакция като шев", :scope => [:admin])
    end
    
  end

  def print
    @sell = Sell.find(params[:id])
    render :layout => 'print'
  end
  
  def update
    @sell = @contact.sells.find(params[:id])
    
    if @sell.update_attributes(params[:sell])
      flash[:notice] = t("Успешно записана", :scope => [:admin, :sells])
      redirect_to edit_admin_contact_sell_path(:id => @sell.id, :key => @sell.contact.key, :contact_id => @sell.contact.id)
      #      edit_admin_contact_path(:id => @sell.contact.id, :key => @sell.contact.key)
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @sell = @contact.sells.find(params[:id])
    @sell.destroy
    redirect_to admin_sells_url
  end

  private
  #--------------------------------
  def belongs_to_contact
    unless @contact
      flash[:error] = "Can't display sell without contact"
      redirect_to :action => "index"
    end
    unless @contact.key == params[:key] or @contact.key
      flash[:error] = "Нямате ключ за да достъпите офертите на контакта"
    end
  end

end

app/views/admin/sells/_form.html.erb
<script type="text/javascript">
  $(document).ready(function() {
    var $tabs = $('#sell_tabs').tabs();
    var $selected = $tabs.tabs('select', '<%= params[:current_tab] || params[:current_tab] = 0 %>' );

    $('.ui-tabs-selected').click(
    function() {
      if ($(this) != $selected) {
        $selected.addClass('ui-tabs-hide');
        $(this).removeClass('ui-tabs-hide');
        $selected = $(this);
      }
    })

    $('form').submit(function() {
      var selected = $tabs.tabs('option', 'selected');
      $('#current_tab').val(selected);
    });

  });
</script>

<div id="sell">
  <div class="clear"></div>
  <h2><%= @sell.offer_type.name %> <%= @sell.property_type.name %></h2>
  <%= semantic_form_for [:admin, @sell.contact, @sell], :html => {:multipart => true} do |form| %>
    <%= form.error_messages %>
    <%= form.input :property_type_id, :as => :hidden, :value => @sell.property_type_id %>
    <%= form.input :client_id, :as => :hidden, :value => @sell.client_id %>
    <%= form.input :offer_type_id, :as => :hidden, :value => @sell.offer_type_id %>

    <%= form.inputs t('Служебна информация', :scope => [:admin, :sells]) do %>
      <% if can? :set_owner, @sell %>
        <%= form.input :user_id,
          :required => true,
          :collection => current_user.my_users.collect{|chield| [chield.email, chield.id]},
          :include_blank => current_user.root?,
          :label => t("Обслужва се от", :scope => [:admin, :sells])
      %>

        <%= form.input :co_owner_id,
          :required => false,
          :collection => current_user.my_users.collect{|chield| [chield.email, chield.id]},
          :include_blank => true,
          :label => t("Възложена на", :scope => [:admin, :sells])
      %>
      <% else %>
        <%= form.input :user_id, :as => :hidden, :value => @sell.user_id %>
        <li><%= @sell.co_owner ? t("Възложена на", :scope => [:admin, :sells]) + " " + @sell.co_owner.email : "" %></li>
      <% end %>

      <%= form.input :canceled_type_id,
        :required => false,
        :collection => CanceledType.all,
        :include_blank => true,
        :label => t("Отказана", :scope => [:admin, :sells])
    %>

      <%= form.input :canceled_until,
        :required => false,
        :as => :calendar,
        :include_blank => true,
        :label => t("Отказана до", :scope => [:admin, :sells])
    %>

      <%=
      form.input :status_id,
        :required => true,
        :as => :select,
        :collection => $cache['Status'].collect{|status| [status.name, status.id]},
        :include_blank => false
    %>
      <%=
      form.input :source_id,
        :required => true,
        :as => :select,
        :collection => $cache['Source'].collect{|source| [source.name, source.id]},
        :include_blank => true
    %>
      <%= form.input :source_value %>
    <% end %>

    <!-- Атрибути на типа имот-->
    <%= form.inputs t('Основни харктеристики', :scope => [:admin, :sells]) do %>
      <%= form.semantic_fields_for :keywords_sells do |keyword_fields_form| %>
        <%= keyword_fields_form.input :keyword_id, :as => :hidden, :value => keyword_fields_form.object.keyword.id %>
        <%= render_keyword(keyword_fields_form, keyword_fields_form.object.keyword) %>
      <% end %>
    <% end %>

    <!-- Описание -->
    <%= form.inputs t('Описание', :scope => [:admin, :sells]) do %>
      <%= form.input :description, :as => :text, :input_html => {:style => 'width: 800px'} %>
    <% end %>

    <!-- Табове -->
    <%= render :partial => 'tabs', :locals => {:form => form} %>

    <%= form.buttons do %>
      <%= form.commit_button  :button_html => { :class => "large" } %>
    <% end %>

  <% end %>

  <%= render :partial => "/admin/shared/timestamps", :locals => {:object => @sell} %>
</div>

app/views/admin/sells/_search_form.html.erb
<script type="text/javascript">
  $(document).ready(function($) {   

  // Change our search form to ajax
    $('#search_form').submit(function() {
      var params = $(this).serialize()
      $.ajax(
      {
        type: "GET",
        url: "<%= tab_offers_admin_contact_path(:id => @contact.id,:key => @contact.key) %>",
        data: params,
        cache: false,
        // ПРОВЕРКА: async: false,
        success: function(html){
          $("#ui-tabs-15").replaceWith(html);
        }
      });
    return false;
    });
})
</script>

<%= form_for @search, :url => tab_offers_admin_contact_path(:id => @contact.id, :key => @contact.key), :html => {:id => "search_form", :method => :get}  do |f| %>
  <% params[:key] = @contact.key %>
  <%= hidden_field_tag "action" %>
  <fieldset>
    <div style="float:left; width: 90%">
      <div style="float:left;">
        <%=  %>
        <%= f.label :id%>
        <%= f.text_field :id %>
      </div>
      <div style="float:left;">
        <%= f.label :property_type_id_equals %>
        <%= f.select :property_type_id_equals, $cache['PropertyType'].collect{|property_type| [property_type.name, property_type.id]}, {:include_blank => true} %>
      </div>
      <div style="float:left;">
        <% offer_sells = $cache['OfferType'].select{|offer_type| (offer_type.tag == "sellers" or offer_type.tag == "renters")} %>
        <%= f.label :offer_type_id_equals %>
        <%= f.select :offer_type_id_equals, offer_sells.collect{|offer_sell| [offer_sell.name, offer_sell.id]}, {:include_blank => true} %>
      </div>
      <div style="float:left;">
        <%= f.label :keywords_tag_like, t("price_from", :scope =>[:admin, :sells, :search_form]) %>
        <%# price = $cache['Keyword'].select{|keyword| keyword.tag == "price"} %>
        <%#= f.hidden_field :keywords_sells_keyword_id, :value => price.id %>
        <%= f.text_field :keywords_sells_value_gt  %>
      </div>
    </div>
    <div style="float:left;">  
      <%= submit_tag t(:search), :key => @contact.key %>
      <%= link_to t(:clear), nil, :class => "clear_form" %>
    </div>
  </fieldset>
<% end %>

app/views/admin/sells/_sell_actions.html.erb
<%=
  link_to t(:edit),
    edit_admin_contact_sell_path(
      :contact_id => contact,
      :id => sell.active_record_id,
      :key => contact.key
    ),
    {
      :class => "action edit",
      :id => "#{sell.active_record_id}_edit"
    } if can?(:edit, sell)
%>

<%=
  link_to t(:show),
    admin_contact_sell_path(
      :contact_id => contact,
      :id => sell.active_record_id,
      :key => sell.contact.key
    ),
    {
      :target => "_blank",
      :class => "action show",
      :id => "#{sell.active_record_id}_show"
    } if can? :show, sell

%><%=
  link_to t("Към проекта", :scope => [:admin, :sells]),
    edit_admin_contact_project_path(
      :contact_id => contact,
      :id => sell.project_id,
      :key => contact.key
    ),
    {      
      :class => "action edit_project",
      :id => "#{sell.project_id}_edit_project"
    } if can?(:edit, sell) and sell.project
%>

app/views/admin/sells/_tabs.html.erb
<%= tabs_for(:id => :sell_tabs) do |tab| %>

  <!-- Адрес-->
  <% tab.create('address', t('tab:Адрес', :scope => [:admin, :sells])) do %>
    <%= form.semantic_fields_for :address, :id => "address_form" do |address|%>
      <%= render :partial => "admin/addresses/address_form", :locals => {:f => address} %>
    <% end %>
    <div class="clear"></div>
  <% end %>

  <!-- Помещения -->
  <% tab.create('rooms', t('tab:Помещения', :scope => [:admin, :sells])) do %>
    <%= form.inputs t(:"tab:Помещения", :scope => [:admin, :sells]), :id => "room_forms" do %>
      <%= nested_edit form, :rooms, "/admin/shared/room_fields",  t("Добави помещение", :scope => [:partials, :rooms]), Proc.new{|item| true }  %>
    <% end %>
  <% end %>

  <!-- Огледи -->
  <% tab.create('inspections', t('tab:Огледи', :scope => [:admin, :sells])) do %>
    <%= form.inputs t(:"Огледи", :scope => [:admin, :sells]), :id => "inspection_forms" do %>
      <%= nested_edit form, :inspections, "/admin/shared/inspection_fields",  t("Добави оглед", :scope => [:partials, :inspections]), Proc.new{|item| !item.new_record? } %>
    <% end %>
  <% end %>

  <!-- Снимки -->
  <% unless form.object.new_record? %>
    <% tab.create('pictures', t('tab:Галерия', :scope => [:admin, :sells])) do %>
      <%= render :partial => 'admin/pictures/list', :locals => {:sell => form.object, :pictures => @pictures}%>
      <%#= form.inputs t(:"Снимки на имота", :scope => [:admin, :sells]), :id => "picture_forms" do %>
        <%#= nested_edit form, :pictures, "/admin/shared/picture_fields", t(:"Добави снимка", :scope => [:partials,  :pictures]), Proc.new{|item| item.picture.file? } %>
      <%# end %>
    <% end %>
  <% end %>

  <!-- Документи-->
  <% tab.create('documents', t('tab:Документи', :scope => [:admin, :sells])) do %>
    <%= form.inputs t(:"Документи на проекта", :scope => [:admin, :project]), :id => "document_forms" do %>
      <%= nested_edit form, :documents, "/admin/shared/document_fields", t(:"Добави файл", :scope => [:partials, :documents]), Proc.new{|item| item.document.file? }  %>
    <% end %>
  <% end %>

<% end %>

app/views/admin/sells/edit.html.erb
<% if @sell.project_id.blank? %>
  <%= breadcrumbs_for_contact(@contact, :contact_sells_index, @sell) %>
<% else %>
  <%= breadcrumbs_for_contact(@contact, :contact_sells_index, @sell.project, @sell) %>
<% end %>


<% title(t("Редакция оферта", :scope => [:admin, :sells], :kind_of => @sell.property_type.name)) %>

<%= render :partial => 'form' %>

app/views/admin/sells/index.html.erb
<% title(t("Оферти предлага",
    :client => @contact.name, :scope => [:admin, :sells]))
%>

<%= breadcrumbs_for_contact(@contact, :contact_sells_index) %>

<div style="clear:both;margin: 0 0 2px 0;">
  <%= render :partial => '/admin/contacts/button_add_sell', :locals => {
    :contact => @contact
  }
%>
</div>

<% if @sells.size > 0 %>
  <%= render :partial => 'admin/shared/sell',
    :collection => @sells,
    :locals => {
    :contact => @contact,
    :actions => "/admin/sells/sell_actions"
  }
%>
  <%= will_paginate @sells  %>
<% else %>
  <p><%= t("Няма оферти Предлага", :scope => [:admin, :sells]) %></p>
<% end %>

app/views/admin/sells/new.html.erb
<% title(t("Нова оферта", :scope => [:admin, :sells], :kind_of => @sell.property_type.name)) %>

<%= render :partial => 'form' %>

app/views/admin/sells/show.html.erb
<% title t("title", :scope => [:admin, :sells, :show]) %>

<% if @sell.project %>
  <%= breadcrumbs_for_contact(@contact, :contact_projects_index, @sell.project, @sell) %>
<% else %>
  <%= breadcrumbs_for_contact(@contact, :contact_sells_index, @sell) %>
<% end %>

<div id="offer_sell_preview" class="ui-widget ui-widget-content ui-corner-all">

  <div class="ui-widget ui-widget-content ui-corner-all column">
    <h2><%= t(:Имот, :scope => [:admin, :sells]) %></h2>
    <div>
      <strong>
        <%= @sell.property_type.name %> <%= @sell.offer_type.name %>
      </strong>
    </div>
    <div>
      <%= t("Код",:scope => [:admin, :sells, :search_results]) %>:
      <b><%= @sell.id %> <%= @sell.status.name %></b>
    </div>

    <%= render :partial => '/admin/shared/show_client', :locals => {:object => @sell} %>

    <div>
      <h2><%= t("Адрес", :scope => [:admin, :sells]) %></h2>
      <br/>
      <strong>
        <%# can?(:peek_offer_from_contact, @sell) ? show_address(@sell.address, :full_array).join("<br/>").html_safe : show_address(@sell.address, :till_street) %>
        <%= show_address(@sell.address, :full_array).join("<br/>").html_safe if @sell.address%>
      </strong>
    </div>
    <br/>

    <div id="sell_keyords">
      <% @sell.keywords_sells.each do |keywords_sell| %>
        <% unless keywords_sell.value.blank? %>
          <div id="keyword">
            <%= show_keyword(@sell, keywords_sell.keyword.tag) %>
          </div>
        <% end %>
      <% end %>
      <br/>
      <% unless @sell.description.blank? %>
        <div id="sell_description" class="ui-widget ui-widget-content ui-corner-all">
          <b>
            <%= t("Описание", :scope => [:admin, :sells]) %> :
          </b>
          <br/>
          <%= @sell.description %>
        </div>
      <% end %>
    </div>

    <br/>


  </div>


  <div class="ui-widget ui-widget-content ui-corner-all column">

    <%= render :partial => '/admin/shared/show_owners', :locals => {:object => @sell} %>

    <div>
      <%= render :partial => '/admin/shared/documents_list', :locals => {:object => @sell} %>
    </div>

    <br/>

    <% if @sell.inspections.count > 0   %>
      <div id="inspections" class="ui-widget ui-widget-content ui-corner-all">
        <h2><%= t("Огледи", :scope => [:admin, :sells]) %></h2>
        <ul>
          <% @sell.inspections.each do |inspection| %>
            <%= content_tag :li, l(inspection.created_at, :format => :human) %>
            <%= content_tag :ul do %>
              <%= content_tag(:li, inspection.description) %>
              <%= content_tag :li, t("Извършен от", :scope => [:admin, :sells, :inspections])  %>
              <%= content_tag :ul do %>
                <%= content_tag(:li, inspection.visit_user.display_name) if inspection.visit_user %>
                <%= content_tag(:li, inspection.first_visit_with_user.display_name) if inspection.first_visit_with_user%>
                <%= content_tag(:li, inspection.second_visit_with_user.display_name) if inspection.second_visit_with_user  %>
                <%= content_tag(:li, inspection.third_visit_with_user.display_name) if inspection.third_visit_with_user %>
                <%= content_tag(:li, inspection.forth_visit_with_user.display_name) if inspection.forth_visit_with_user %>
                <%= content_tag(:li, inspection.fifth_visit_with_user.display_name) if inspection.fifth_visit_with_user %>
              <% end %>
            <% end %>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= render :partial => "/admin/shared/timestamps", :locals => {:object => @sell} %>

  </div>



  <div class="clear"></div>
  <br/>

  <div class="ui-widget ui-widget-content ui-corner-all ">
    <% if @sell.project %>
      <%= render :partial => '/admin/projects/basic_data', :locals => {:project => @sell.project } %>
    <% end %>
  </div>

</div>

<% if @sell.pictures.size > 0 %>
  <div id="sell_galery" <%# style="page-break-before: always" %>>
    <% @sell.pictures.each do |picture| %>
      <div class="no_page_break">
        <%= image_tag picture.url(:normal) %>
        <br/>
        <%= picture.description %>
      </div>
    <% end %>
  </div>
<% end %>

<script type="text/javascript">
  $(document).ready(function() {
    //   window.print();
  })
</script>